### ISSUE TITLE
Move the wiki! Milestone on NixOS

### ISSUE THREAD

**Issue by samueldr** [nix-community/wiki#27]
# https://github.com/NixOS/nixpkgs/milestone/8

*This is a tracking issue for the wiki project.*

**Comment by Mic92** [comment]
Move the wiki to the wiki?

**Comment by makefu** [comment]
It is about moving wiki information into the manual. however we could comment on issues guerillia style and link to the new wiki

**Comment by samueldr** [comment]
Yes, and to hopefully close over a hundred issues in nixpkgs, well, there are many issues that won't be closed, but some can be.

Can easily be closed

 * Already moved articles
 * Irrelevant articles that should (have been|be) deleted
 * Stub articles that will not be moved.
