### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by colemickens** [nix-community/wiki#32]
Can we have markdown support? I'm finding a lot of things like "Nix applications that use opengl on non-NixOS platforms" that require digesting a number of Issues, installing and testing a number of tools, etc, that I would like to document.

Currently, it's a bit of friction to contribute these as I have to reference the mediawiki syntax instead of markdown, which I sadly write as fluently as anything else these days.

**Comment by Mic92** [comment]
No. This is not supported by mediawiki.

**Comment by fadenb** [comment]
Perhaps http://pandoc.org/try/?text=&from=markdown&to=MediaWiki is something to get you started.

**Comment by colemickens** [comment]
The pandoc conversion seems much more the direction I'm interested in and accommodates me without needing server changes. It works, thank you both.
