### ISSUE TITLE
Follow wiki instruction to create nixos in GCE but failed.

### ISSUE THREAD

**Issue by YuMingLiao** [nix-community/wiki#33]
Failed at this step:

gcloud compute images create nixos-14125424c9ef9f7-x86-64-linux --source-uri gs://nixos-images/nixos-14.12.542.4c9ef9f7-x86_64-linux.raw.tar.gz

ERROR: (gcloud.compute.images.create) Could not fetch resource:
 - Forbidden

**Comment by YuMingLiao** [comment]
Hi, @Mic92 
Thanks for the quick response!
But how to use that file?
I tried to use in the latest image in that file, but still get error.

```
gcloud compute images create nixos-1803132536fdb5ba4cdf9-x86-64-linux
 --source-uri gs://nixos-cloud-images/nixos-image-18.03.132536.fdb5ba4cdf9-x86_64-linux.raw.tar.gz
ERROR: (gcloud.compute.images.create) Could not fetch resource:
 - Forbidden
```

**Comment by Mic92** [comment]
Last time I used nixops to deploy something on google cloud:
https://github.com/Mic92/dotfiles/blob/master/nixos/vms/gce.nix

I think I also used this script https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/gce/create-gce.sh at some point to upload a new image to my own bucket.

**Comment by YuMingLiao** [comment]
Thanks for the guidance! I'll give it a shot.

**Comment by makefu** [comment]
@Mic92 thanks for the cleanup :+1:
