### ISSUE TITLE
Licensing and paid services

### ISSUE THREAD

**Issue by mintyc** [nix-community/wiki#34]
Hunted around the web site/wiki etc but there does not appear to be a clear description of copyright assignment, licensing and distinctions between 'open' components and paid services.

This lack of transparency is off putting. Perhaps you could add explicit items in the FAQ section of your wiki to clarify.

Given the need to monetise, I'm not concerned about the distinction, I'd just like to understand it so I don't become dependent on something I can't control....

**Comment by mintyc** [comment]
Further context from Hackernews thread at https://news.ycombinator.com/item?id=26687873#26688136
Abbreviated here:
Mmmm, no. Nix is not a SaaS that builds your snapshots that you have to pay for (or that "they need to monotize", what's wrong with people?),

> Your snapshots and abilities to rollback etc are likely to be dependent on their storage servers

Not sure where you get this from. Snapshots are stored locally unless you specify otherwise, and then you'll get to chose whatever storage servers you want to use. Absolutely no "hidden" costs with Nix as it's a MIT licensed project and I don't think they even offer any "value-added" services nor paid customer support.

Edit: reading the issue you just created (https://github.com/nix-community/wiki/issues/34), I'm even more confused. "Given the need to monetise" is coming from where?

My response:

I'm really impressed with it and am ONLY seeking clarity. I'll be extremely happy if I can use it standalone. Copyright, licensing are all I'm looking at.
e.g. Something like AGPL is considered copyleft and not compatible with 'open source' ethos. Still 'free' but the additional non-compete cloud service clause is both a sensible move, but something I'd just like to understand.

Your statement of 'what's wrong with people' is what is getting me. Borderline defensive. I'm definitely not knocking the product, quite the reverse. Its so good I want to embrace it wholeheartedly.

I have no problem paying for things, contributing voluntarily to a great product.

Its good to see that various organisations are committed to funding the infrastructure costs etc. (which negates my comment about storage servers).

As to monetisation, kind of irrelevant but was referring to paid services at the bottom of https://nixos.wiki/wiki/Nix_Ecosystem

**Comment by Mic92** [comment]
Regarding finance: You can donate to the NixOS foundation to ensure storage can be paid in future: https://opencollective.com/nixos All commercial `services` in the lower section have pricing on their own web site.
Regarding licensing: Every project page of the same site has a license in their repository. But you are free to add
this license to each wiki page as well.

**Comment by grahamc** [comment]
The paid services at the bottom of that wiki page are services not affiliated with NixOS.org. They're run by users and contributors to the Nix ecosystem. You don't need to pay for anything to use Nix and Nixpkgs and NixOS, it is all free. It isn't free like a freemium free, either. Everything is local. If our binary cache goes away, it is just a cache: you can build it all locally.

**Comment by tomberek** [comment]
At first I was also puzzled by this comment, but looking at our front pages I could not find a clear statement about what license the various Nix/Nixpkgs/NixOS projects were under. I know it's on the GitHub pages, but didn't see that on https://nixos.org. Perhaps we add a statement or two? (@garbas )

@mintyc: added a column about the licenses and a statement to the bottom to that wiki page to make this clearer, thanks!

**Comment by mintyc** [comment]
Thanks for all replies.

@tomberek Great news on the clarification.

Closing and looking forward to using this impressive project.
