### ISSUE TITLE
'Contributing' wiki page doesn't state how to flag an article or parts of an article

### ISSUE THREAD

**Issue by Narice** [nix-community/wiki#36]
The NixOS 'Contributing' wiki page doesn't talk about how to flag an article as out of date,in need of a rewrite etc.
It is however a very important part of wiki as first of all it states to the user that the information is possibly erroneous and second of all, it signifies to the maintainer(s) of the page that the information in the page is not sufficient, badly written of out-of date.

**Comment by Mic92** [comment]
I think there is a template for that: https://nixos.wiki/wiki/Template:Outdated Feel free to add this contributing article.

**Comment by Narice** [comment]
Oh woaw thanks, I'll try to put that in today.
I'll close the issue when it is done.
I'll probably make a section on templates most probably

**Comment by Narice** [comment]
Ok I have added a link to the help page for templates in the find stuff to do section of the wiki!
