### ISSUE TITLE
Modern editor plugins, like Wikipedia

### ISSUE THREAD

**Issue by mweinelt** [nix-community/wiki#40]
Wikipedia currently uses these two and offers one or the other:

- https://www.mediawiki.org/wiki/Extension:VisualEditor
- https://www.mediawiki.org/wiki/Extension:WikiEditor

And I feel both of them are alot more pleasant that that we are currently using.

**Comment by jooooscha** [comment]
Yes, please. I started to contribute recently, but the current editor really is a chore to use.
If I can be of any help in accelerating this, please tell me how

**Comment by Mic92** [comment]
For starters a up-to-date php and mediawiki running on a maintained version of NixOS would be nice to have. Unfortunately the current admin does not see this a necessity and it is very hard to reach out to him in person.

**Comment by jooooscha** [comment]
What is the current setup like? Is there anything we can do about it?

**Comment by Mic92** [comment]
implemented at https://wiki.nixos.org/
