### ISSUE TITLE
Sessions citing vscode-with-extensions are missing parens in function calls

### ISSUE THREAD

**Issue by felipegssantos** [nix-community/wiki#42]
I followed the second snippet in [the VSCodium page](https://nixos.wiki/wiki/VSCodium) to set up vscodium and extensions, but nix wouldn't build my configuration. It turned out there was a syntax error [as pointed out in this discussion](https://discourse.nixos.org/t/nixos-rebuild-fails-to-build-a-configuration-with-vscode-with-extensions-even-though-the-expression-works-in-nix-repl/). Because of the missing parens, `vscode-with-extensions.override {vscodeExtensions = my-extensions}` are two elements of a list instead of being the result of applying a function to a set. I don't know how many sessions are affected, but we should probably fix that.

**Comment by Mic92** [comment]
Fixed.
