### ISSUE TITLE
Correction - Oh-My-Zsh

### ISSUE THREAD

**Issue by berts83231** [nix-community/wiki#45]
Incorrect
`programs.zsh.ohMyZsh.enable`

Corrected Version

```
programs.zsh = {
  ... # Your zsh config
  oh-my-zsh = {
    enable = true;
    plugins = [ "git" "thefuck" ];
    theme = "robbyrussell";
  };
};
```

See https://rycee.gitlab.io/home-manager/options.html#opt-programs.zsh.oh-my-zsh

**Comment by Mic92** [comment]
Fixed. Btw you can also use your github login to changes things in the wiki.

**Comment by berts83231** [comment]
Thanks. I'll do that in the future.
