### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by jooooscha** [nix-community/wiki#46]
As far as I can tell, there is a small group of people who actively edit pages and contribute to the wiki.
But, my question is if the wiki's backend alive.

Is anyone actively maintaining the media wiki instance? 
I see some issues here (#13, #17, #21, #24, #29, #31, #35, #39, #40) that seems to be stale for years, but still relevant.
Therefore, I have the feeling that no one who has control over the backend server infrastructure is actively working on it.

Therefore, I have two questions: Is my observation wrong, and secondly, if not, can somebody else take over?

**Comment by Mic92** [comment]
The content of the wiki is still actively maintained. However fadenb who owns the domain and the server is mostly unresponsive and actively ignores our attempts to contact him. I am still making backups in case it will disappear from the internet. Also read this: https://github.com/NixOS/nix.dev/issues/279

**Comment by jooooscha** [comment]
Ok, I think I have a better understanding of the situation now. But it seems, there is little hope that fadenb will help in making this project official and (the backend) actively maintained, right?

**Comment by adam248** [comment]
Would it be best to ask if we can have [wiki.nixos.org](https://nixos.org/) point to https://nixos.wiki for now and if something bad happens someone else or even nixos.org could spin up a wiki instance and even have a github repo?

**Comment by Mic92** [comment]
We could setup wiki.nix-community.org but the webserver would also accept requests for this vhost and I doubt it would (and it would also not have ssl certificates in this case).
