### ISSUE TITLE
Secure Boot Section Different from lanzaboote docs

### ISSUE THREAD

**Issue by MasterMach50** [nix-community/wiki#48]
The [secure boot section](https://nixos.wiki/wiki/Secure_Boot) of the nixos wiki specifies to `reset all secure boot keys in uefi` while the [lanzaboote quick start guide](https://github.com/nix-community/lanzaboote/blob/master/docs/QUICK_START.md) explicitly tells not to do this.

Although this is the main issue there are still some inconsistencies between the wiki and the docs (like the flake.nix file)

**Comment by MasterMach50** [comment]
From my personal experience the only method to enable secure boot that works and does not corrupt my windows install on the same drive is following the [lanzaboote quick start guide](https://github.com/nix-community/lanzaboote/blob/master/docs/QUICK_START.md) and use a niv project rather than nix flakes (as specified in the lanzaboote quick start guide).

**Comment by Mic92** [comment]
What makefu said.
