### ISSUE TITLE
Unable to submit edits?

### ISSUE THREAD

**Issue by J-Swift** [nix-community/wiki#49]
When I try to make an edit to a page (fixing a copy/paste error on https://nixos.wiki/index.php?title=Distributed_build) it gets blocked by cloudflare.
<img width="600" alt="image" src="https://github.com/nix-community/wiki/assets/734158/b51075d8-52f2-4e81-857d-32ba565765a0">

Tried on both chrome and firefox, same issue.

**Comment by Artturin** [comment]
This isn't a repo for wiki support, email `admin-team@nixos.wiki`.

**Comment by makefu** [comment]
what @Artturin said. In general, nixos.wiki is behind cloudflare which may block your ip address for one reason or another

**Comment by Mic92** [comment]
I had the same issue. It's the webapplication firewall from cloudflare. I put some work into a mediawiki NixOS configuration for a NixOS wiki: https://github.com/Mic92/nixos-wiki-infra
However at the time I am not really to face the discussions / drama that would come up with setting up yet another wiki. There are people in https://matrix.to/#/#nixos-wiki2:matrix.org that discuss the topic. Hopefully we get some backing from the NixOS infra team to have some domain under nixos.org...
