### ISSUE TITLE
Reasons why MediaWiki is on 1.29, A version from 2017

### ISSUE THREAD

**Issue by Artturin** [nix-community/wiki#50]
So far the wiki team hasn't released a clear reason why it's impossible/implausible to update MediaWiki and it's extensions.

Hopefully they will answer the question here once and for all.

~I am going to email a link to this issue to `admin-team@nixos.wiki`.~ Done

If there are impassable blockers to upgrading the software then please give your approval on creating a new wiki controlled by `NixOS` or `nix-community`.

https://nixos.wiki/wiki/Special:Version

**Comment by makefu** [comment]
@Artturin thanks for the initiative!

**Comment by Artturin** [comment]
No response to me, @zimbatm emailed the wiki team as a NixOS foundation member and offered to partner on the wiki, however their response was basically "NO".

**Comment by Mic92** [comment]
Fixed. We now have https://wiki.nixos.org
