### ISSUE TITLE
LISP page

### ISSUE THREAD

**Issue by ekliptik** [nix-community/wiki#51]
Hi! There is none. Emacs doesn't count. As I try LISP out, I could contribute the absolute basics without assuming prior LISP experience.

**Comment by Mic92** [comment]
Just do it. The login is for free.

**Comment by ekliptik** [comment]
Hi Mic, thank you for your clear and helpful suggestion to "Just do it". MediaWiki says that when you search for a page that doesn't exist, you get an option to create the missing page. This is not true on the nixOS wiki, so I assumed regular contributors don't have the power to create pages. The "Contributing" page on nixOS wiki doesn't mension creating pages either. It looks like manually typing the URL to a page that doesn't exist is the only way to create it.

**Comment by Mic92** [comment]
The deployed mediawiki is severe outdated just now. We are trying to make an official instance over christmas, since the current admin doesn't want to update it. Hopefully than the user experience becomes better.
