### ISSUE TITLE
Keyboard Layout Customization is out of date

### ISSUE THREAD

**Issue by ddogfoodd** [nix-community/wiki#54]
[This page](https://nixos.wiki/wiki/Keyboard_Layout_Customization) of the wiki seems to be out of date.

Specifically the "Advanced configuration with xmodmap" part doesn't seem to work anymore.
There is even a discussion post stating the same.

**Comment by makefu** [comment]
Hi! You can just go ahead and edit the page to fix the topic or at least mark the section as out of date. You can log in either with your github account or create a new account
